openapi: "3.0.3"
info:
  title: "ktor_test API"
  description: "ktor_test API"
  version: "1.0.0"
servers:
  - url: "https://ktor_test"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExposedUser"
        required: true
      description: "Show your name!"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExposedUser"
  /users/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExposedUser"
components:
  schemas:
    ExposedUser:
      type: object
      properties:
        name:
          type: string
          example: pingping
        age:
          type: integer
          format: int64
          example: 29
      xml:
        name: exposedUser
